include: package:very_good_analysis/analysis_options.5.1.0.yaml

exclude:
  - "**/*.g.dart"

language:
  strict-casts: true
  strict-inference: true
  strict-raw-types: true

errors:
  invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
