// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    } else if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for your platform - '
        'you can configure them by running the FlutterFire CLI again.',
      );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbPAp6jqXUoM64QERJhfFoYaW3gcLo7eU',
    appId: '1:730582626364:android:550780ddee3a4780d99339',
    messagingSenderId: '730582626364',
    projectId: 'our-budget-531d8',
    storageBucket: 'our-budget-531d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAXUx2nAKSUu2D5lzsRsAp09DDJSzeiH0',
    appId: '1:730582626364:ios:a9eb2cfcf84edff0d99339',
    messagingSenderId: '730582626364',
    projectId: 'our-budget-531d8',
    storageBucket: 'our-budget-531d8.appspot.com',
    iosBundleId: 'com.kaemi',
  );
}
